version: 0.2

phases:
    build:
        commands:
            - echo Building...
    artifacts:
        files:
        - serverless/index.html
        - serverless/favicon.ico
        - serverless/styles/*
        - serverless/images/*
